source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "sinatra", "~> 2.0"
gem "shotgun", "~> 0.9.2"
gem "envyable", "~> 1.2"

gem "puma", "~> 6.0"
