# WireStarter - maintained by support@signalwire.com
version: "3.7"

services:

  wirestarter:
    image: signalwire/wirestarter
    environment:
     - WORKDIR= ${WORKDIR:-workdir}
     - VISUAL=${VISUAL:-vim}
    container_name: wirestarter
    command: ["/start_services.sh"]
    env_file: ../.env
    volumes:
      - "${WORKDIR}:/workdir"
      - "opt:/opt"
    stdin_open: true
    tty: true
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        python_version: "python3.9"
    privileged: true
    networks:
      wirestarter:
        ipv4_address: 172.50.0.100

volumes:
  opt:

networks:
  wirestarter:
    external: true
