
# This file extends docker-compose.yml
version: "3.7"

services:

  wirestarter:
    image: signalwire/wirestarter
    environment:
     PROJECT_ID: ${PROJECT_ID}
     REST_API_TOKEN: ${REST_API_TOKEN}
     NGROK_TOKEN: ${NGROK_TOKEN}
     SIGNALWIRE_SPACE: ${SIGNALWIRE_SPACE}
     LOCALTONET_API_TOKEN: ${LOCALTONET_API_TOKEN}
     LOCALTONET_AUTH_TOKEN: ${LOCALTONET_AUTH_TOKEN}
     WORKDIR: ${WORKDIR:-workdir}
     VISUAL: ${VISUAL:-vim}
    container_name: wirestarter
    command: ["/start_services.sh"]
    env_file: ../.env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${WORKDIR}:/workdir"
      - "opt:/opt"
    ports:
      - 9080:9080/tcp
    stdin_open: true
    tty: true
    build:
      context: ../
      dockerfile: docker/Dockerfile
    privileged: true
    networks:
      wirestarter:
        ipv4_address: 172.50.0.100

volumes:
  opt:

networks:
  wirestarter:
    external: true
