
# This file extends docker-compose.yml
version: "3.7"

services:

  wirestarter:
    image: signalwire/wirestarter
    command: ["/root/start_services.sh"]
    env_file: ../.env
    volumes:
      - storage:/usr/local
    ports:
      - 443:443/tcp
      - 80:80/tcp
    stdin_open: true
    tty: true
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        PROJECT_ID: ${PROJECT_ID}
        REST_API_TOKEN: ${REST_API_TOKEN}
        NGROK_TOKEN: ${NGROK_TOKEN}
        SIGNALWIRE_SPACE: ${SIGNALWIRE_SPACE}
        VISUAL: ${VISUAL}
    privileged: true
    networks:
      wirestarter:
        ipv4_address: 172.50.0.100

volumes:
  storage:

networks:
  wirestarter:
    external: true